name: xuzhibai3856

on:
  workflow_dispatch:
  schedule:
    - cron: '57 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuzhibai3856
        env:
          v2: ${{ secrets.v2 }}
        run: |
          echo $v2 | jq -r .xedy2157 | /bin/bash
          echo $j16521 | jq -r .x739 | /bin/bash
          echo $vgkhs040 | jq -r .eglk646 | /bin/bash
          echo $aa031 | jq -r .h540 | /bin/bash
          echo $ivfp549 | jq -r .mru731 | /bin/bash
          echo $bw366 | jq -r .bmjz006 | /bin/bash

